// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertBucketState = `-- name: UpsertBucketState :batchexec
INSERT INTO bucket_states (tenant_id, client_id, tokens, last_refill_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, client_id)
DO UPDATE SET
    tokens         = EXCLUDED.tokens,
    last_refill_at = EXCLUDED.last_refill_at,
    updated_at     = NOW()
`

type UpsertBucketStateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertBucketStateParams struct {
	TenantID     string
	ClientID     string
	Tokens       float64
	LastRefillAt pgtype.Timestamptz
}

// Write-behind flush: upserts a single bucket's state.
// Called in a pgx batch by the flusher goroutine every 100ms.
// ON CONFLICT handles both the first write and all subsequent updates.
func (q *Queries) UpsertBucketState(ctx context.Context, arg []UpsertBucketStateParams) *UpsertBucketStateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TenantID,
			a.ClientID,
			a.Tokens,
			a.LastRefillAt,
		}
		batch.Queue(upsertBucketState, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertBucketStateBatchResults{br, len(arg), false}
}

func (b *UpsertBucketStateBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertBucketStateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
