// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: configs.sql

package db

import (
	"context"
)

const loadConfigs = `-- name: LoadConfigs :many
SELECT
    tenant_id,
    client_id,
    capacity::float8    AS capacity,
    refill_rate::float8 AS refill_rate
FROM  rate_limit_configs
WHERE tenant_id = $1
  AND is_active = TRUE
ORDER BY client_id
`

type LoadConfigsRow struct {
	TenantID   string
	ClientID   string
	Capacity   float64
	RefillRate float64
}

// Loads all active rate-limit configurations for a tenant.
// capacity is cast to float8 so sqlc generates float64, matching the bucket's type.
func (q *Queries) LoadConfigs(ctx context.Context, tenantID string) ([]LoadConfigsRow, error) {
	rows, err := q.db.Query(ctx, loadConfigs, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadConfigsRow
	for rows.Next() {
		var i LoadConfigsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ClientID,
			&i.Capacity,
			&i.RefillRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
