// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BucketState struct {
	ID           int64
	TenantID     string
	ClientID     string
	Tokens       float64
	LastRefillAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RateLimitConfig struct {
	ID         int64
	TenantID   string
	ClientID   string
	Capacity   int32
	RefillRate float64
	IsActive   bool
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}
