// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: states.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadBucketStates = `-- name: LoadBucketStates :many
SELECT
    tenant_id,
    client_id,
    tokens::float8 AS tokens,
    last_refill_at
FROM  bucket_states
WHERE tenant_id = $1
ORDER BY client_id
`

type LoadBucketStatesRow struct {
	TenantID     string
	ClientID     string
	Tokens       float64
	LastRefillAt pgtype.Timestamptz
}

// Loads persisted token counts for all clients of a tenant.
// Used once at startup to restore in-memory bucket state.
func (q *Queries) LoadBucketStates(ctx context.Context, tenantID string) ([]LoadBucketStatesRow, error) {
	rows, err := q.db.Query(ctx, loadBucketStates, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoadBucketStatesRow
	for rows.Next() {
		var i LoadBucketStatesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ClientID,
			&i.Tokens,
			&i.LastRefillAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
